pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - status-success=Travis CI - Pull Request
    actions:
      merge:
        method: merge
  - name: automatic merge for Dependabot/travis with actual conditions pull requests
    conditions:
      - author=dependabot-preview[bot]
      - status-success=continuous-integration/travis-ci/pr
    actions:
      merge:
        method: merge
